apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels: 
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce   # EBS supports only RWO (one node at a time)
  resources:
    requests:
      storage: 3Gi
  storageClassName: default